name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy).$(Date:MMdd)$(Rev:.r)

variables:
  - group: GitHubPATGroup
  - name: SolutionFile
    value: miNationalrot.sln
  - name: BuildConfiguration 
    value: Release
  - name: VersionPrefix
    value: '0'
  - name: BuildYear
    value: $[format('{0:yy}', pipeline.startTime)]
  - name: BuildDate
    value: $[format('{0:MMdd}', pipeline.startTime)]
  - name: Revision
    value: 0
  - name: VersionExt
    value: '0.0.0.0'
      
stages:
- stage: 'Build'    
  displayName: 'Build by Nuke'
  jobs:
  - job: DotNetBuild
    pool:
      #name: Hosted Windows 2019 with VS2019
      name: Default

    steps:
    - task: UseNode@1
        
    - powershell: |
        $m = dotnet tool list --global | Where {$_.StartsWith("nuke.globaltool")}
        $m.Count
        If ($m.Count -eq '0') 
        {  
          Write-Host 'Installing Nuke tool...'
          dotnet tool install -g Nuke.GlobalTool 
        }
        else
        {
          Write-Host 'Nuke tool already installed.'
        }

    - script: |
          nuke -GitHub_PAT %PAT%
      displayName: 'Publish to GitHub Pages'
      env:
         PAT: $(github_pat2)
