name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy).$(Date:MMdd)$(Rev:.r)
variables:
  - group: GitHubPATGroup
  - name: SolutionFile
    value: miNationalrot.sln
  - name: BuildConfiguration 
    value: Release
  - name: VersionPrefix
    value: '0'
  - name: BuildYear
    value: $[format('{0:yy}', pipeline.startTime)]
  - name: BuildDate
    value: $[format('{0:MMdd}', pipeline.startTime)]
  - name: Revision
    value: 0
  - name: VersionExt
    value: '0.0.0.0'
      
stages:
- stage: 'Build'    
  displayName: 'Build by Nuke'
  jobs:
  - job: DotNetBuild
    pool:
      #name: Hosted Windows 2019 with VS2019
      name: Default

    steps:
    - powershell: |
        $m = dotnet tool list --global | Where {$_.StartsWith("nuke.globaltool")}
        if ($m.Count eq 0) 
        {
            dotnet tool install -g Nuke.GlobalTool
        }

    - task: CmdLine@2
      displayName: 'Run Nuke'
      inputs:
        script: |
          nuke
