
variables:
  Parameters.RestoreBuildProjects: miNationalrot.sln
  BuildConfiguration: Release

stages:
- stage: Build    
  jobs:
  - job: Build
    pool:
      name: Hosted Windows 2019 with VS2019
      #name: Default

    steps:
   
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 3.0.100-preview6-012264'
      inputs:
        version: 3.0.100-preview6-012264

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(Parameters.RestoreBuildProjects)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(Parameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(Parameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: 'drop' 

- stage: Deploy
  jobs:
   - job: Deploy
     pool:
      name: Hosted Windows 2019 with VS2019

     steps:

      - task: DownloadBuildArtifacts@0
        displayName: Download Build Artifacts to '$(System.ArtifactsDirectory)'
        inputs:
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)' 

      - task: ExtractFiles@1
        displayName: 'Extract files'
        inputs:
          archiveFilePatterns: '$(System.ArtifactsDirectory)\*.zip' 
          destinationFolder: '$(build.artifactstagingdirectory)\disttmp'

      - task: AccidentalFish.githubpages-publish.AccidentalFish.GitHubPages-Publish.GitHubPagesPublish@1
        displayName: 'Publishes to GitHub Pages'
        inputs:
          docPath: '$(build.artifactstagingdirectory)\disttmp'
          githubusername: miNationalrot
          githubemail: 'remo.oser@osisa.com'
          githubaccesstoken: 25b8d6180428e6d7c052399d5ceb08cfdab3cbb5
          repositoryname: miNationalrot
          branchname: master